### ISSUE TITLE
Loosing context

### ISSUE THREAD

**Issue by ai** [FormidableLabs/react-shuffle#11]
I use Flummox, so every component has `flux` context.

But If I will wrap them to `<Shuffle>` I will get warning from React:

```
Warning: owner-based and parent-based contexts differ (values: `[object Object]` vs `undefined`) for key (flux) while mounting Social (see: http://fb.me/react-context-by-parent)
```

**Comment by kenwheeler** [comment]
Not sure if this is fixable. The context loss is due to the use of `cloneElement`, which is required. You could pass the flux instance down explicitly as a prop for the short term, as this behavior will be fixed in the 0.14 release of React.

**Comment by ai** [comment]
Awesome. Thank for advice. I think I can wait for 0.14.

**Comment by ai** [comment]
@kenwheeler thanks again for quick 1.0 release. Everything is works and we have less warnings :).

But I still get:

```
Warning: Failed Context Types: Required context `flux` was not specified in `Social`. Check the render method of `Socials`.
```

Seems like clone in ReactShuffle has no context. What we can do with it?

**Comment by ai** [comment]
@kenwheeler any updates? This issue is really annoing.

Redux BTW is big `context` user too.

**Comment by kenwheeler** [comment]
Any suggestions? Try to reapply the context on the clones?

**Comment by ai** [comment]
Manually reappling context is a dangerous solution, because you can miss a fixing `prop`.

Why `context` is even loosing right now? Why we can solve it?

**Comment by kenwheeler** [comment]
Assuming due to clones? I'll look into it more

**Comment by ai** [comment]
Yeap, context is lost in clones.

**Comment by ai** [comment]
Any updates? Do you need some help?

**Comment by kenwheeler** [comment]
PRs are certainly welcome
