### ISSUE TITLE
React 0.14 release

### ISSUE THREAD

**Issue by ai** [FormidableLabs/react-shuffle#16]
Wait for quick release. Current version with React 0.13 produce a lot of warnings because of `cloneWithProps` and `context`.

@kenwheeler

**Comment by kenwheeler** [comment]
On it. Refactoring a ton of my repos for 0.14 over the next few days.

**Comment by kenwheeler** [comment]
Just cut 1.0.0, enjoy

**Comment by ai** [comment]
Great work. Thanks for quick fix.
